module.exports = {
	belt              : {
		name   : "Giant's Belt",
		perk   : '+200 Base Health',
		id     : 'giantsbelt',
		combos : {
			glove   : 'trapclaw',
			sword   : 'zekesherald',
			rod     : 'morellonomicon',
			bow     : 'titanichydra',
			tear    : 'redemption',
			vest    : 'redbuff',
			cloak   : 'zephyr',
			belt    : 'warmogsarmor',
			spatula : 'frozenmallet',
		},
	},
	bow               : {
		id     : 'recurvebow',
		name   : 'Recurve Bow',
		perk   : '+20% Attack Speed',
		combos : {
			glove   : 'repeatingcrossbow',
			sword   : 'giantslayer',
			rod     : 'guinsoosrageblade',
			bow     : 'rapidfirecannon',
			tear    : 'statikkshiv',
			vest    : 'phantomdancer',
			cloak   : 'runaanshurricane',
			spatula : 'bladeoftheruinedking',
			// belt    : 'titanichydra',
		},
	},
	cloak             : {
		id     : 'negatroncloak',
		name   : 'Negatron Cloak',
		perk   : '+20 Magic Resist',
		combos : {
			glove   : 'quicksilver',
			sword   : 'bloodthirster',
			rod     : 'ionicspark',
			tear    : 'hush',
			vest    : 'swordbreaker',
			cloak   : 'dragonsclaw',
			spatula : 'talismanoflight',
			// bow     : 'runaanshurricane',
			// belt    : 'zephyr',
		},
	},
	glove             : {
		id     : 'sparringgloves',
		name   : 'Sparring Gloves',
		perk   : '+10& Dodge Chance, +10% Crit Chance',
		combos : {
			glove   : 'thiefsgloves',
			sword   : 'infinityedge',
			rod     : 'jeweledgauntlet',
			tear    : 'handofjustice',
			vest    : 'iceborngauntlet',
			spatula : 'berserkeraxe',
			// bow     : 'repeatingcrossbow',
			// cloak   : 'quicksilver',
			// belt    : 'trapclaw',
		},
	},
	rod               : {
		id     : 'needlesslylargerod',
		name   : 'Needlessly Large Rod',
		perk   : '+20% Spell Power',
		combos : {
			sword   : 'hextechgunblade',
			rod     : 'rabadonsdeathcap',
			tear    : 'ludensecho',
			vest    : 'locketoftheironsolari',
			spatula : 'infernocinder',
			// glove   : '',
			// bow     : '',
			// cloak   : '',
			// belt    : '',
		},
	},
	spatula           : {
		id     : 'spatula',
		name   : 'Spatula',
		perk   : 'Something',
		combos : {
			sword   : 'youmuusghostblade',
			tear    : 'magescap',
			vest    : 'wardensmail',
			spatula : 'forceofnature',
			// glove   : '',
			// rod     : '',
			// bow     : '',
			// cloak   : '',
			// belt    : '',
		},
	},
	sword             : {
		name   : 'B.F. Sword',
		perk   : '+20 Attack Damage',
		id     : 'bfsword',
		combos : {
			sword : 'deathblade',
			tear  : 'spearofshojin',
			vest  : 'guardianangel',
			// glove   : 'infinityedge',
			// rod     : 'hextechgunblade',
			// bow     : 'giantslayer',
			// cloak   : 'bloodthirster',
			// belt    : 'zekesherald',
			// spatula : 'youmuusghostblade',
		},
	},
	tear              : {
		id     : 'tearofthegoddess',
		name   : 'Tear of the Goddess',
		perk   : '+20% Starting Mana',
		combos : {
			tear : 'seraphsembrace',
			vest : 'frozenheart',
			// glove   : '',
			// sword   : '',
			// rod     : '',
			// bow     : '',
			// cloak   : '',
			// belt    : '',
			// spatula : '',
		},
	},
	vest              : {
		name   : 'Chain Vest',
		perk   : '+20 Armor',
		id     : 'chainvest',
		combos : {
			vest : 'thornmail',
			// sword   : 'guardianangel',
			// glove   : 'iceborngauntlet',
			// rod     : 'locketoftheironsolari',
			// bow     : 'phantomdancer',
			// tear    : 'frozenheart',
			// cloak   : 'swordbreaker',
			// belt    : 'redbuff',
			// spatula : 'wardensmail',
		},
	},

	// 'swordvest': {

	// }
	belt_belt       : {id: 'warmogsarmor'},
	belt_bow        : {id: 'titanichydra'},
	belt_cloak      : {id: 'zephyr'},
	belt_glove      : {id: 'trapclaw'},
	belt_rod        : {id: 'morellonomicon'},
	belt_spatula    : {id: 'frozenmallet'},
	belt_sword      : {id: 'zekesherald'},
	belt_tear       : {id: 'redemption'},
	belt_vest       : {id: 'redbuff'},
	bow_bow         : {id: 'rapidfirecannon'},
	bow_cloak       : {id: 'runaanshurricane'},
	bow_glove       : {id: 'repeatingcrossbow'},
	bow_rod         : {id: 'guinsoosrageblade'},
	bow_spatula     : {id: 'bladeoftheruinedking'},
	bow_sword       : {id: 'giantslayer'},
	bow_tear        : {id: 'statikkshiv'},
	bow_vest        : {id: 'phantomdancer'},
	cloak_cloak     : {id: 'dragonsclaw'},
	cloak_glove     : {id: 'quicksilver'},
	cloak_rod       : {id: 'ionicspark'},
	cloak_spatula   : {id: 'talismanoflight'},
	cloak_sword     : {id: 'bloodthirster'},
	cloak_tear      : {id: 'hush'},
	cloak_vest      : {id: 'swordbreaker'},
	glove_glove     : {id: 'thiefsgloves'},
	glove_rod       : {id: 'jeweledgauntlet'},
	glove_spatula   : {id: 'berserkeraxe'},
	glove_sword     : {id: 'infinityedge'},
	glove_tear      : {id: 'handofjustice'},
	glove_vest      : {id: 'iceborngauntlet'},
	rod_rod         : {id: 'rabadonsdeathcap'},
	rod_spatula     : {id: 'infernocinder'},
	rod_sword       : {id: 'hextechgunblade'},
	rod_tear        : {id: 'ludensecho'},
	rod_vest        : {id: 'locketoftheironsolari'},
	spatula_spatula : {id: 'forceofnature'},
	spatula_sword   : {id: 'youmuusghostblade'},
	spatula_tear    : {id: 'magescap'},
	spatula_vest    : {id: 'wardensmail'},
	sword_sword     : {id: 'deathblade'},
	sword_tear      : {id: 'spearofshojin'},
	sword_vest      : {id: 'guardianangel'},
	tear_tear       : {id: 'seraphsembrace'},
	tear_vest       : {id: 'frozenheart'},
	vest_vest       : {id: 'thornmail'},
	
	// guardianangel     : {
	// 	name : 'Guardian Angel',
	// 	perk : 'Revives champ with 400 HP after 2s',
	// },
	// deathblade        : {
	// 	name : 'Death Blade',
	// 	perk : 'On kill or assist, gain +15 attack. Stacks infinitely.',
	// },

	// 	_combos: [ 'beltbelt',
	//   'beltbow',
	//   'beltcloak',
	//   'beltglove',
	//   'beltrod',
	//   'beltspatula',
	//   'beltsword',
	//   'belttear',
	//   'beltvest',
	//   'bowbow',
	//   'bowcloak',
	//   'bowglove',
	//   'bowrod',
	//   'bowspatula',
	//   'bowsword',
	//   'bowtear',
	//   'bowvest',
	//   'cloakcloak',
	//   'cloakglove',
	//   'cloakrod',
	//   'cloakspatula',
	//   'cloaksword',
	//   'cloaktear',
	//   'cloakvest',
	//   'gloveglove',
	//   'gloverod',
	//   'glovespatula',
	//   'glovesword',
	//   'glovetear',
	//   'glovevest',
	//   'rodrod',
	//   'rodspatula',
	//   'rodsword',
	//   'rodtear',
	//   'rodvest',
	//   'spatulaspatula',
	//   'spatulasword',
	//   'spatulatear',
	//   'spatulavest',
	//   'swordsword',
	//   'swordtear',
	//   'swordvest',
	//   'teartear',
	//   'tearvest',
	// 	'vestvest',
	// ]
};
